// Package x_go_type_override_on_ref provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/livesession/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package x_go_type_override_on_ref

// ResponseBase defines model for response.Base.
type ResponseBase struct {
	Id *string `json:"id,omitempty"`
}

// ResponsePlaceholder defines model for response.Placeholder.
type ResponsePlaceholder = Placeholder
