// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/livesession/oapi-codegen/v2 version v2.0.0-00010101000000-000000000000 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Person defines model for Person.
type Person struct {
	// Embedded struct due to allOf(#/components/schemas/PersonProperties)
	PersonProperties `yaml:",inline"`
	// Embedded fields due to inline allOf schema
}

// PersonProperties These are fields that specify a person. They are all optional, and
// would be used by an `Edit` style API endpoint, where each is optional.
type PersonProperties struct {
	FirstName          *string `json:"FirstName,omitempty"`
	GovernmentIDNumber *int64  `json:"GovernmentIDNumber,omitempty"`
	LastName           *string `json:"LastName,omitempty"`
}

// PersonWithID defines model for PersonWithID.
type PersonWithID struct {
	// Embedded struct due to allOf(#/components/schemas/Person)
	Person `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	ID int64 `json:"ID"`
}

// PersonWithRole defines model for PersonWithRole.
type PersonWithRole struct {
	// Embedded struct due to allOf(#/components/schemas/Person)
	Person `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	Role string `json:"Role"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/5RVTY/jNgz9K4Tao+HMokUPvi2adhGg2AbtbPewGWAYi460lSlVoicwgvz3QrLzhWy7",
	"Oz7xQD3yPT7SB9X6PngmlqSag0qtoR5LuKaYPOcInfu9U82ng/o+Uqca9d3i8moxP1lM+evoA0WxlNSx",
	"OqhI/ww2klbNJ/WrjUneY0+qUr/hHD4dnyqlKbXRBrG5nno0NoFNgBAKZAV7KwZ6ZI3i4whdBgJkDQ6T",
	"AGNPFWwHAV8g0MFquWEe+i3FGgrc3g9Ow5YgkgyRScN2BITndyTPkGR0BG/Xqxo+EvQUdwRiaC6/4XDm",
	"NHWC7MVQhD8Lc9gb2xrw7EYI0b9YTQlOvKGz5HSqN6wqJWMg1Si//UytqGOl7iRrDndaUCLASDMQiEGB",
	"FKi13XhWKJOksaShc2cZqqzRhs/chzTzZnj+Rdtr5kCsg7csFewNRQLC1uQhnLAmBuGm1ctAm8OJXJJo",
	"eZfJvfMvFLknltXyfZlFTut87FFUoyzLTz9eRLEstKOYH569cY96/E8RP1oxq+Vr3Vo8ektqAvlqm8fq",
	"xtur5bc4GSK1PmrAdPFhF30PCD9HQqHzGGpYCbSeBS2nDeepZkfOJvAdIKyvlwMZUGs72z9S8kNsCT58",
	"WC3/13tZtj+8o9cL92WyQkky3yl7cqvBBFsvBqwk8HuGq33KS5x7z6UhUkeRuKV6w4+GYEdMEYU0tF4T",
	"JFOMTP2WdFHj/KrAWHaWp8W9LfIl65443/vreqol6+lOvJxmufMFwEpGUo+F+NvSUVEtlWGoSr1QTJNC",
	"b+qH+iFr7wMxBqsa9UP9UL/J3aGY0tgiOGzJeKenfdmR3F+Fv9DZcgsT7JEFUMBRPoWeCTJUBcmD5IH0",
	"+Dflq0E9GAxhnMTIUmAGW2nVqPVVySxACp7T6Rp1OLjSQnYjcQkxBGfbArD4PP8kponn6OvumZe1CHnL",
	"7Jr9sXz/BgAA//+GXQSVogYAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
